version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    volumes:
      # Only mount source code for hot-reloading in development
      # Remove if you don't want it to overwrite built code!
      - ./src:/app  # assuming your source code is in a subfolder 'src'
    # If your Dockerfile handles /app, avoid overwriting it entirely!

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: threat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - db

volumes:
  pgdata:
  grafana-storage:
