version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: threatdb
      POSTGRES_USER: threatuser
      POSTGRES_PASSWORD: threatpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - db

  app:
    build: ./app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app:/app
    command: ["python3", "main.py"]

volumes:
  pgdata: