apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: db:5432
    database: threat_db
    user: postgres
    password: postgres
    isDefault: true
    jsonData:
      sslmode: disable
