apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: threat_db
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
